#!/bin/bash

# 🎉 HOSTA CLOUD - PROJETO COMPLETO
# Guia Rápido de Uso

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           🚀 HOSTA CLOUD - SERVER MANAGEMENT PLATFORM          ║"
echo "║                                                                ║"
echo "║  Painel Pterodactyl + Provedores VPS Gratuitos - All-in-One   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 O que foi adicionado ao seu projeto:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ BACKEND COMPLETO (Node.js + Express)"
echo "   └─ Pasta: server/"
echo "   └─ Endpoints: Pterodactyl + VPS"
echo "   └─ Porta: 5000"
echo ""

echo "✅ COMPONENTES FRONTEND"
echo "   ├─ PanelManager.tsx      (Gerenciar painéis)"
echo "   ├─ ServerList.tsx        (Listar servidores)"
echo "   ├─ VPSProviderList.tsx   (Provedores gratuitos)"
echo "   └─ ServerMonitoringDashboard.tsx (Monitoramento real-time)"
echo ""

echo "✅ PÁGINA PAINEL PTERODACTYL"
echo "   └─ http://localhost:5173/pterodactyl"
echo ""

echo "✅ DOCUMENTAÇÃO COMPLETA"
echo "   ├─ README_NEW.md         (Overview do projeto)"
echo "   ├─ SETUP.md              (Instalação passo a passo)"
echo "   ├─ DEPLOY.md             (Deploy em produção)"
echo "   └─ CHANGELOG.md          (Resumo das mudanças)"
echo ""

echo "✅ DOCKER CONFIGURADO"
echo "   ├─ docker-compose.yaml"
echo "   ├─ Dockerfile.frontend"
echo "   ├─ Dockerfile.backend"
echo "   └─ start.sh              (Script automático)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🚀 COMO COMEÇAR:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "OPÇÃO 1: Script Automático (Recomendado)"
echo "  $ chmod +x start.sh"
echo "  $ ./start.sh"
echo ""

echo "OPÇÃO 2: Instalação Manual"
echo "  Backend:"
echo "    $ cd server"
echo "    $ npm install"
echo "    $ npm run dev"
echo ""
echo "  Frontend (outro terminal):"
echo "    $ npm install"
echo "    $ npm run dev"
echo ""

echo "OPÇÃO 3: Docker"
echo "  $ docker-compose up -d"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🌐 ACESSAR O SISTEMA:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Frontend:           http://localhost:5173"
echo "  Backend API:        http://localhost:5000"
echo "  Painel Pterodactyl: http://localhost:5173/pterodactyl"
echo "  Health Check:       http://localhost:5000/api/health"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📚 DOCUMENTAÇÃO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Leia: README_NEW.md              (Overview)"
echo "  2. Setup: SETUP.md                  (Instalação)"
echo "  3. Deploy: DEPLOY.md                (Produção)"
echo "  4. Detalhes: CHANGELOG.md           (Mudanças)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🔧 RECURSOS GERENCIADOS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Pterodactyl Panels:"
echo "    ├─ Adicionar painéis (públicos, sem autenticação)"
echo "    ├─ Listar servidores por painel"
echo "    ├─ Monitorar recursos (CPU, RAM, Disk)"
echo "    └─ Gerenciar múltiplos painéis"
echo ""
echo "  Provedores VPS Gratuitos:"
echo "    ├─ GratisVPS (gratisvps.net)"
echo "    ├─ VPSFree (vpsfree.org)"
echo "    ├─ Oracle Cloud"
echo "    ├─ AWS Free Tier"
echo "    └─ Google Cloud"
echo ""
echo "  Dashboard Real-time:"
echo "    ├─ Monitoramento de CPU"
echo "    ├─ Uso de memória"
echo "    ├─ Espaço em disco"
echo "    └─ Uptime dos servidores"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "⚙️  CONFIGURAÇÃO DE AMBIENTE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Frontend (.env.local):"
echo "    VITE_API_URL=http://localhost:5000/api"
echo ""
echo "  Backend (server/.env):"
echo "    PORT=5000"
echo "    NODE_ENV=development"
echo "    CORS_ORIGIN=http://localhost:5173"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🛠️  ENDPOINTS DA API:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Pterodactyl:"
echo "    POST   /api/pterodactyl/panels/add"
echo "    GET    /api/pterodactyl/panels"
echo "    GET    /api/pterodactyl/panels/:id/servers"
echo "    GET    /api/pterodactyl/panels/:id/servers/:serverId/resources"
echo ""
echo "  VPS:"
echo "    GET    /api/vps/providers"
echo "    GET    /api/vps/providers/gratisvps"
echo "    GET    /api/vps/providers/vpsfree"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📊 TECNOLOGIAS USADAS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Frontend:"
echo "    ├─ React 18"
echo "    ├─ Vite"
echo "    ├─ TypeScript"
echo "    ├─ Tailwind CSS"
echo "    └─ shadcn/ui"
echo ""
echo "  Backend:"
echo "    ├─ Node.js"
echo "    ├─ Express.js"
echo "    ├─ TypeScript"
echo "    └─ Axios"
echo ""
echo "  Deployment:"
echo "    ├─ Docker"
echo "    ├─ Nginx"
echo "    └─ PM2"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "💡 DICAS IMPORTANTES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Sempre inicie ambos (frontend e backend)"
echo "  2. Use as variáveis .env.example como base"
echo "  3. Verifique CORS_ORIGIN em produção"
echo "  4. Teste o painel no navegador antes de usar"
echo "  5. Monitore os logs em development"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🆘 PROBLEMAS COMUNS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  CORS Error:"
echo "    → Verificar CORS_ORIGIN em server/.env"
echo ""
echo "  Port já em uso:"
echo "    → Mudar PORT em server/.env"
echo ""
echo "  Módulos não encontrados:"
echo "    → npm install && cd server && npm install"
echo ""
echo "  Panel não conecta:"
echo "    → Verificar URL do painel"
echo "    → Confirmar que painel está online"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ PRÓXIMAS ETAPAS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Executar start.sh para iniciar"
echo "  2. Acessar http://localhost:5173/pterodactyl"
echo "  3. Adicionar um painel Pterodactyl"
echo "  4. Explorar os recursos"
echo "  5. Ler documentação para features avançadas"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║      🎉 Hosta Cloud está pronto para uso!                     ║"
echo "║                                                                ║"
echo "║   Execute: ./start.sh                                          ║"
echo "║   ou: npm run dev (em um terminal) + npm run dev em server/   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
